AutoRepairService/Areas/Admin/Controllers/OrderController.cs
using AutoRepairService.Core.IServices;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepairService.Areas.Admin.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService service;

        public OrderController(IOrderService _service)
        {
            service = _service;
        }

        public async Task<IActionResult> All()
        {
            var model = await service.AllOrdersAsync();
            return View(model);
        }
        public async Task<IActionResult> Dispatch(int id)
        {
            await service.DispatchAsync(id);
            return RedirectToAction(nameof(All));
        }
    }
}

AutoRepairService/Areas/Admin/Controllers/RepairController.cs
using AutoRepairService.Core.IServices;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepairService.Areas.Admin.Controllers
{
    public class RepairController : BaseController
    {
        private readonly IRepairAdministrationService service;

        public RepairController(IRepairAdministrationService _service)
        {
            service = _service;
        }

        public async Task<IActionResult> All()
        {
            var allRepairs = await service.GetAllRepairsAsync();

            return View(allRepairs);
        }

        public async Task<IActionResult> Active()
        {
            var repairs = await service.ReviewActiveRepairs();
            return View(repairs);
        }

        public async Task<IActionResult> Pending()
        {
            var repairs = await service.ReviewPendingRepairs();
            return View(repairs);
        }

        public async Task<IActionResult> Declined()
        {
            var repairs = await service.ReviewDeclinedRepairs();
            return View(repairs);
        }


        public async Task<IActionResult> Details(int id)
        {
            //if ((await service.RepairExistAsync(id)) == false)
            //{
            //    TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
            //    return RedirectToAction("All", "Repair");
            //}

            var model = await service.RepairDetailsAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Approve(int id)
        {
            //if ((await service.RepairExistAsync(id)) == false)
            //{
            //    TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
            //    return RedirectToAction("All", "Repair");
            //}

            await service.ApproveRepairAsync(id);
            var repairs = await service.ReviewPendingRepairs();
            return View("Pending", repairs);
        }

        public async Task<IActionResult> Decline(int id)
        {
            //if ((await service.RepairExistAsync(id)) == false)
            //{
            //    TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
            //    return RedirectToAction("All", "Repair");
            //}

            await service.DeclineRepairAsync(id);
            var repairs = await service.ReviewPendingRepairs();
            return View("Pending", repairs);
        }


    }
}

AutoRepairService/Controllers/CarController.cs
using AutoRepairService.Core.IServices;
using AutoRepairService.Core.ViewModels.Car;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AutoRepairService.Core.Constants;

namespace AutoRepairService.Controllers
{
    [AllowAnonymous]
    public class CarController : Controller
    {
        private readonly ICarService service;
        private readonly ILogger<CarController> logger;

        public CarController(ICarService _service, ILogger<CarController> _logger)
        {
            service = _service;
            logger = _logger;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllCarsQueryModel query)
        {
            try
            {
                var result = await service.AllCarsAsync(
                query.Category,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllCarsQueryModel.CarsPerPage);

                query.TotalCarsCount = result.TotalCarsCount;
                query.Categories = await service.AllCategoriesNames();
                query.Cars = result.Cars;

                return View(query);
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }
        }

        //[HttpGet]
        //public async Task<IActionResult> All()
        //{
        //    try
        //    {
        //        var cars = await service.GetAllCarsAsync();
        //        return View(cars);
        //    }
        //    catch (Exception ms)
        //    {
        //        TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
        //        logger.LogError(ms.Message, ms);
        //        return RedirectToAction("Index", "Home");
        //    }          
        //}

    }
}

AutoRepairService/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepairService.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        public IActionResult LiveChat()
        {
            return View();
        }
    }
}

AutoRepairService/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoRepairService</title>
    <link rel="stylesheet" href="~/lib/pace/minimal.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoRepairService.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>
    <partial name="_AdminMessages" />

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoRepairService</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Repairs
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Repair" asp-action="All">All</a></li>
                                <li><a class="dropdown-item" asp-controller="Repair" asp-action="Active">Active</a></li>
                                <li><a class="dropdown-item" asp-controller="Repair" asp-action="Pending">Pending</a></li>
                                <li><a class="dropdown-item" asp-controller="Repair" asp-action="Declined">Declined</a></li>

                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Car
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Car" asp-action="Add">Add</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Car" asp-action="All">All</a></li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Statistic" asp-action="All">
                                Statistics

                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="All">
                                Orders

                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Chat" asp-action="MessageRequest">
                                Messages
                            </a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @(DateTime.UtcNow.Year != ReleaseYear ? $"{ReleaseYear}-{DateTime.UtcNow.Year}" : $"{ReleaseYear}") AutoRepairService
        </div>
    </footer>
    <script src="~/lib/pace/pace.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutoRepairService/Areas/Admin/Views/Shared/_AdminMessages.cshtml
@if (TempData[MessageConstant.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstant.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.WarningMessage] != null)
{
    <script>
        $(function () { toastr.warning('@TempData[MessageConstant.WarningMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.success('@TempData[MessageConstant.SuccessMessage].ToString()'); });
    </script>
}

AutoRepairService/Areas/Admin/Views/Shared/_CarDetailsAdminPartial.cshtml
@model CarViewModel

<div class="modal fade" id="exampleModal_@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@Model.Brand Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Model.Description

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                @*                <button type="button" class="btn btn-primary">Understood</button>
                *@
            </div>
        </div>
    </div>
</div>

AutoRepairService/Areas/Admin/Views/Shared/_CarFormPartial.cshtml
@model CarModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Brand"></label>
                <input asp-for="Brand" class="form-control" placeholder="Brand">
                <span asp-validation-for="Brand" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelOfCar"></label>
                <input asp-for="ModelOfCar" class="form-control" placeholder="ModelOfCar">
                <span asp-validation-for="ModelOfCar" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage"></label>
                <input asp-for="Mileage" class="form-control" placeholder="Mileage">
                <span asp-validation-for="Mileage" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year"></label>
                <input asp-for="Year" class="form-control" placeholder="Year">
                <span asp-validation-for="Year" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="Price">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" rows="5" placeholder="Description.."> </textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Image Url">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.CarCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3 " type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

AutoRepairService/Areas/Admin/Views/Shared/_OrderDetailsPartial.cshtml
@model OrderServiceViewModel

<div class="modal fade" id="staticBackdrop_@Model.OrderNumber" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Order details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Model.Details
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
@*                <button type="button" class="btn btn-primary">Understood</button>
*@            </div>
        </div>
    </div>
</div>