AutoRepairService/Controllers/MechanicController.cs
using AutoRepairService.Core.Constants;
using AutoRepairService.Core.IServices;
using AutoRepairService.Core.ViewModels.Mechanic;
using AutoRepairService.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepairService.Controllers
{


    [Authorize]
    public class MechanicController : Controller
    {
        private readonly IMechanicService service;
        private readonly ILogger<MechanicController> logger;

        public MechanicController(
            IMechanicService _service,
            ILogger<MechanicController> _logger)
        {
            service = _service;
            logger = _logger;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            try
            {
                var model = await service.AllMechanicsAsync();
                return View(model);
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Customer)]
        public IActionResult Become()
        {
            var model = new BecomeMechanicViewModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Customer)]
        public async Task<IActionResult> Become(BecomeMechanicViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await service.AddMechanicAsync(User.Id(), model);
                return RedirectToAction("JoinMechanics", "User");
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpGet]
        public IActionResult RateMechanic(string id, int repairId)
        {
            var model = new MechanicRatingModel()
            {
                MechanicId = id,
                UserId = User.Id(),
                RepairId = repairId
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> RateMechanic(string id, int repairId, MechanicRatingModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await service.RateMechanicAsync(User.Id(), id, repairId, model);
                return RedirectToAction("MyRepairs", "Repair");
            }
            catch (Exception ms)
            {
                logger.LogError(ms.Message, ms);
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                return RedirectToAction("Index", "Home");
            }

        }
    }
}

AutoRepairService/Views/Mechanic/All.cshtml
@model IEnumerable<MechanicViewModel>

@{
    ViewBag.Title = "All Mechanics";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
@if (User.IsInRole("Repairer"))
{ //change form with <a>
    <div class="text-center">
        <a asp-controller="Mechanic" asp-action="Become" class="btn btn-success mb-2">Join Our Mechanics</a>
    </div>
}
<div class="text-center row">
    @if (Model.Any())
    {
        @foreach (var mechanic in Model)
    {
        <div class="card col-4" style="width: 20rem;">
            <div class="card-body">
                <p class="mb-0">@mechanic.FirstName</p>
                <p class="mb-0">@mechanic.LastName</p>
                <p class="mb-0">Phone number: @mechanic.PhoneNumber</p>
                <p class="mb-0">Rating: @mechanic.Rating</p>
            </div>
        </div>
    }
    }
    else
    {
        <h3>No mechanics available</h3>
    }
</div>

AutoRepairService/Views/Mechanic/Become.cshtml
@model BecomeMechanicViewModel

@{
    ViewBag.Title = "Enter your information";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" placeholder="First name">
                <span asp-validation-for="FirstName" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" placeholder="Last name">
                <span asp-validation-for="LastName" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" placeholder="Phone number">
                <span asp-validation-for="PhoneNumber" class="small text-danger"></span>
            </div>        
            <div class="text-center">
                <input class="btn btn-primary mt-3 " type="submit" value="Join" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AutoRepairService/Views/Mechanic/RateMechanic.cshtml
@model MechanicRatingModel


<link rel="stylesheet" href="~/css/star.css">

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        
        
        
        <form method="post">
            <div class="form-group">
                <h4 class="text-center">How you rate the mechanic</h4>
                <div class="rating" onclick="setValue()">

                    <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
                    <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                    <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
                    <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
                    <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
                </div>

                <input type="hidden" id="points_value" asp-for="Points" value="0">
                <span asp-validation-for="Points" class="small text-danger"></span>
              

                <textarea asp-for="Comment" rows="5" class="form-control" placeholder="Comment.."></textarea>
                <span asp-validation-for="Comment" class="small text-danger"></span>


                <input type="hidden" asp-for="MechanicId" class="form-control" value="@Model.MechanicId">
                <input type="hidden" asp-for="UserId" class="form-control" value="@Model.UserId">
                <input type="hidden" asp-for="RepairId" class="form-control" value="@Model.RepairId">            
            
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3 " type="submit" value="Rate" />
            </div>
        </form>
    </div>
</div>



<script>
    function setValue() {
        var value = 0;

        if (document.querySelector('input[name="rating"]:checked') != null) {
            value = document.querySelector('input[name="rating"]:checked').value;
        }

        var element = document.querySelector('input[id="points_value"]');

        element.value = parseInt(value);
    }
</script>