AutoRepairService/Controllers/CarController.cs
using AutoRepairService.Core.IServices;
using AutoRepairService.Core.ViewModels.Car;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using AutoRepairService.Core.Constants;

namespace AutoRepairService.Controllers
{
    [AllowAnonymous]
    public class CarController : Controller
    {
        private readonly ICarService service;
        private readonly ILogger<CarController> logger;

        public CarController(ICarService _service, ILogger<CarController> _logger)
        {
            service = _service;
            logger = _logger;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllCarsQueryModel query)
        {
            try
            {
                var result = await service.AllCarsAsync(
                query.Category,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllCarsQueryModel.CarsPerPage);

                query.TotalCarsCount = result.TotalCarsCount;
                query.Categories = await service.AllCategoriesNames();
                query.Cars = result.Cars;

                return View(query);
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }
        }

        //[HttpGet]
        //public async Task<IActionResult> All()
        //{
        //    try
        //    {
        //        var cars = await service.GetAllCarsAsync();
        //        return View(cars);
        //    }
        //    catch (Exception ms)
        //    {
        //        TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
        //        logger.LogError(ms.Message, ms);
        //        return RedirectToAction("Index", "Home");
        //    }          
        //}

    }
}

AutoRepairService/Controllers/CartController.cs
using AutoRepairService.Core.Constants;
using AutoRepairService.Core.IServices;
using AutoRepairService.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepairService.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartService service;
        private readonly ILogger<CartController> logger;

        public CartController(ICartService _service, ILogger<CartController> _logger)
        {
            service = _service;
            logger = _logger;
        }

        public async Task<IActionResult> ViewCart()
        {
            try
            {
                var model = await service.ViewCart(User.Id());

                return View(model);

            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Add(int id)
        {
            try
            {
                await service.AddToCart(id, User.Id());
                TempData[MessageConstant.SuccessMessage] = "Car added to your cart";

                return RedirectToAction("All", "Car");
            }
            catch (Exception ms)
            {
                //logger log exception
                TempData[MessageConstant.ErrorMessage] = ms.Message;
                logger.LogError(ms.Message, ms);
                return RedirectToAction("All", "Car");
            }
        }

        public async Task<IActionResult> Remove(int id)
        {
            try
            {
                await service.RemoveFromCart(id, User.Id());
                TempData[MessageConstant.SuccessMessage] = "Car removed from your cart";

                return RedirectToAction(nameof(ViewCart));
            }
            catch (Exception ms)
            {
                //logger log exception
                TempData[MessageConstant.ErrorMessage] = "Something went wrong";
                logger.LogError(ms.Message, ms);
                return RedirectToAction(nameof(ViewCart));
            }
        }

        public async Task<IActionResult> Checkout(IFormCollection collection)
        {

            try
            {
                await service.CheckoutCart(collection, User.Id());
                TempData[MessageConstant.SuccessMessage] = "Order is sent!";
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("All", "Car");
        }

        public async Task<IActionResult> MyOrder()
        {
            try
            {
                var model = await service.MyOrder(User.Id());
                return View(model);
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

AutoRepairService/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepairService.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        public IActionResult LiveChat()
        {
            return View();
        }
    }
}

AutoRepairService/Controllers/OfferController.cs
using AutoRepairService.Core.Constants;
using AutoRepairService.Core.IServices;
using AutoRepairService.Core.ViewModels.Offer;
using AutoRepairService.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace AutoRepairService.Controllers
{
    [Authorize]
    public class OfferController : Controller
    {
        private readonly IOfferService service;
        private readonly ILogger<OfferController> logger;

        public OfferController(IOfferService _service, ILogger<OfferController> _logger)
        {
            service = _service;
            logger = _logger;
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Mechanic)]
        public IActionResult Send()
        {
            var model = new OfferViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Mechanic)]
        public async Task<IActionResult> Send(int id, OfferViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await service.SendOfferAsync(model, id, User.Id());
                TempData[MessageConstant.SuccessMessage] = "Offer sent";
                return RedirectToAction("All", "Repair");
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = ms.Message;
                logger.LogError(ms.Message, ms);
                return RedirectToAction("All", "Repair");
            }


        }



        [HttpGet]
        [Authorize(Roles = RoleConstants.Mechanic)]
        public async Task<IActionResult> OffersCondition()
        {
            try
            {
                var offersCondition = await service.OffersConditionAsync(User.Id());
                return View(offersCondition);
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpGet]
        [Authorize(Roles = $"{RoleConstants.Administrator}, {RoleConstants.Customer}")]
        public async Task<IActionResult> Accept(int id)
        {
            try
            {
                await service.AcceptOfferAsync(id);
                return RedirectToAction("RepairOffers", "Repair");
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }


        }


        [HttpGet]
        [Authorize(Roles = $"{RoleConstants.Administrator}, {RoleConstants.Customer}")]
        public async Task<IActionResult> Decline(int id)
        {
            try
            {
                if (await service.OfferExists(id))
                {
                    var offer = await service.GetOfferAsync(id);
                    await service.DeclineOfferAsync(id);
                }
                return RedirectToAction("RepairOffers", "Repair");
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        [Authorize(Roles = RoleConstants.Mechanic)]
        public async Task<IActionResult> Delete(string id, int offerId)
        {
            try
            {
                await service.RemoveOfferAsync(id, offerId);
                return RedirectToAction(nameof(OffersCondition));
            }
            catch (Exception ms)
            {
                TempData[MessageConstant.ErrorMessage] = "Something went wrong!";
                logger.LogError(ms.Message, ms);
                return RedirectToAction(nameof(OffersCondition));
            }
        }
    }
}

AutoRepairService/Views/Shared/_CarDetailsPartial.cshtml
@model CarViewModel

<div class="modal fade" id="exampleModal_@Model.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@Model.Brand Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Model.Description

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                @*                <button type="button" class="btn btn-primary">Understood</button>
                *@
            </div>
        </div>
    </div>
</div>

AutoRepairService/Views/Shared/_CarPartial.cshtml
@model CarViewModel

<div class="card col-4" style="width: 20rem;">
    <img class="card-img-top" src="@Model.ImageUrl" alt="Car Image">
    <div class="card-body">
        <h5 class="card-title mt-1">@Model.Brand</h5>
        <p class="mb-0">Model: @Model.ModelOfCar</p>
        <p class="mb-0">Price: @Model.Price</p>
        @*@String.Format("{0:f2}", Model.PricePerMonth) BGN*@
        <p class="mb-0">Mileage: @Model.Mileage</p>
        <p class="mb-0">Made: @Model.Year</p>
        <p class="mb-0">Category: @Model.Category</p>
    </div>
    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal_@Model.Id">
        Details
    </a>
    <partial name="_CarDetailsPartial" model="@Model" />
    <br>
    <a asp-controller="Cart" asp-action="Add" asp-route-id="@Model.Id" class="btn btn-success mb-2">Add to Cart</a>
</div>

AutoRepairService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] AutoRepairService</title>
    <link rel="stylesheet" href="~/lib/pace/minimal.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoRepairService.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>

    <partial name="_UserMessages" />

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoRepairService</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (!(User?.Identity?.IsAuthenticated ?? false))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Repair" asp-action="All">Repairs</a>
                            </li>
                        }

                        @if ((User?.Identity?.IsAuthenticated ?? false))
                        {
                            @if (User.IsInRole("Mechanic"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Repair" asp-action="All">Repairs</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Repairs
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Repair" asp-action="MyRepairs">My Repairs</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Repair" asp-action="Add">Add</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Repair" asp-action="All">All</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Repair" asp-action="RepairOffers">My Repairs Offers</a></li>
                                    </ul>
                                </li>
                            }
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="All">Cars</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mechanic" asp-action="All">Mechanics</a>
                        </li>

                        @if ((User?.Identity?.IsAuthenticated ?? false) && User.IsInRole("Mechanic"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="OffersCondition">Offers Condition</a>
                            </li>
                        }

                        @if ((User?.Identity?.IsAuthenticated ?? false) && User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin" asp-action="Index">ADMINISTRATION</a>
                            </li>
                        }

                    </ul>
                    <partial name="_MenuPartial" />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @(DateTime.UtcNow.Year != ReleaseYear ? $"{ReleaseYear}-{DateTime.UtcNow.Year}" : $"{ReleaseYear}") AutoRepairService
        </div>
    </footer>
    <script src="~/lib/pace/pace.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutoRepairService/Views/Shared/_MenuPartial.cshtml
@inject SignInManager<User> SignInManager

@if (SignInManager.IsSignedIn(User))
{
<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
            </svg>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" asp-area="" asp-controller="Cart" asp-action="MyOrder">My orders</a></li>
                @if(!(User.IsInRole("Administrator")))
                {
                    <li><a class="dropdown-item" asp-area="" asp-controller="Chat" asp-action="LiveChat">Live Support</a></li>
                }
        </ul>
    </li>

    <li>
        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">
            
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart" viewBox="0 0 17 17">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
            </svg>
        </a>
    </li>
</ul>
} 

AutoRepairService/Views/Shared/_RepairFormPartial.cshtml
@model RepairModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">

            <div class="form-group">
                <label asp-for="Brand"></label>
                <input asp-for="Brand" class="form-control" placeholder="Repair brand">
                <span asp-validation-for="Brand" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CarModel"></label>
                <input asp-for="CarModel" class="form-control" placeholder="Repair carModel">
                <span asp-validation-for="CarModel" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" rows="5" placeholder="Description.."> </textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.RepairCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3 " type="submit" value="Save"/>
            </div>
        </form>
    </div>
</div>

AutoRepairService/Views/Shared/_UserMessages.cshtml
@using Skydiving.Core.Constants


@if (TempData[MessageConstant.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstant.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.WarningMessage] != null)
{
    <script>
        $(function () { toastr.warning('@TempData[MessageConstant.WarningMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.success('@TempData[MessageConstant.SuccessMessage].ToString()'); });
    </script>
}